mybatis-plus:
  type-aliases-package: com.hsst.skbzhms
  mapper-locations: classpath*:mapper/**/*.xml
  global-config:
    banner: false
    db-config:
      id-type: auto
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    object-wrapper-factory: com.baomidou.mybatisplus.extension.MybatisMapWrapperFactory
